import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from '@/styles/Page1.module.scss';
export default function Page1() {
  const router = useRouter();
  console.log(router);
  const { query } = router;

  const { contract } = query;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1>Contract: {contract} </h1>
        <p>And some other new stuff...</p>
      </main>
    </>
  );
}
