import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from '@/styles/Diamond.module.scss';
import { Diamond, Facets, Storages } from '@/components';
import { IStoragaData } from '@/types';
export default function Page1() {
  const router = useRouter();
  console.log(router);
  const { query } = router;

  const { contract } = query;

  const storages: IStoragaData[] = [
    {
      logo: '📦',
      name: 'Smashcraft.Backpack.Storage',
      description: '💠 Simple(Movement)',
    },
    {
      logo: '🧭',
      name: 'Smashcraft.Worldmap.Storage',
      description: '💠 Simple(Movement)',
    },
    {
      logo: '📦',
      name: 'Smashcraft.CraftReceipt.Storage',
      description: '💠 Simple(Movement)',
    },
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Storages storages={storages} />
        <Facets />
        <Diamond />
      </main>
    </>
  );
}
