name: Diamond Blueprinter build and deploy

on:
  push:
    branches: '*'
  pull_request:
    branches: [ main,  3-kemberlite-contract ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
#          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Compile
        run: yarn compile
      - name: Test
        run: yarn test
      - name: Save Compile Artifacts
        id: artifacts-save
        uses: actions/upload-artifact@v3
        with:
          path: ./backend/artifacts
          name: ${{github.run_id}}-artifacts
      - name: Restore Compile Artifacts
        id: artifacts-restore
        uses: actions/download-artifact@v3
        with:
          name: ${{github.run_id}}-compile
